#!/bin/bash

#####Set Scheduler Configuration Directives#####

#Name the job:
#$ -N BayesFit

#Start script in current working directory
#$ -cwd

#####End Set Scheduler Configuration Directives#####


#####Resource Selection Directives#####

#See the HPC wiki for complete resource information: https://wiki.uiowa.edu/display/hpcdocs/Argon+Cluster
#Select the queue to run in
#$ -q TEMPLIN

#Request four cores
#$ -pe smp 16
#$ -l mf=64G 
#$ -l mem_free=64G

#####End Resource Selection Directives#####
apptainer exec Templin-Stack-2025-01.sif Rscript drafts/runSimulation.R $SGE_TASK_ID
